// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckReaderStatus():Promise<main.ReaderStatus>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetAutoReadStatus():Promise<boolean>;

export function GetLatestData():Promise<string>;

export function GetReaderStatus():Promise<main.ReaderStatus>;

export function GetSavedDataFiles():Promise<Array<string>>;

export function LoadDataFromFile(arg1:string):Promise<string>;

export function OpenDataDirectory():Promise<void>;

export function ReadAndSaveCardData():Promise<main.MyKadData>;

export function ReadCardData():Promise<main.MyKadData>;

export function ReadMyKad():Promise<string>;

export function SaveDataToJSON(arg1:main.MyKadData):Promise<string>;

export function SetAutoRead(arg1:boolean):Promise<void>;
