// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckReaderStatus() {
  return window['go']['main']['App']['CheckReaderStatus']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoReadStatus() {
  return window['go']['main']['App']['GetAutoReadStatus']();
}

export function GetLatestData() {
  return window['go']['main']['App']['GetLatestData']();
}

export function GetReaderStatus() {
  return window['go']['main']['App']['GetReaderStatus']();
}

export function GetSavedDataFiles() {
  return window['go']['main']['App']['GetSavedDataFiles']();
}

export function LoadDataFromFile(arg1) {
  return window['go']['main']['App']['LoadDataFromFile'](arg1);
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function ReadAndSaveCardData() {
  return window['go']['main']['App']['ReadAndSaveCardData']();
}

export function ReadCardData() {
  return window['go']['main']['App']['ReadCardData']();
}

export function ReadMyKad() {
  return window['go']['main']['App']['ReadMyKad']();
}

export function SaveDataToJSON(arg1) {
  return window['go']['main']['App']['SaveDataToJSON'](arg1);
}

export function SetAutoRead(arg1) {
  return window['go']['main']['App']['SetAutoRead'](arg1);
}
